@startuml
|Менеджер фирмы|
start
:Заключение контракта;
:Обращение в банк \nс просьбой об оплате;

|Экономист отдела банка по работе \nсо счетами клиентов|
:Выдача пустого бланка\nзаявления на международный перевод;

|Менеджер фирмы|
:Получение заполненного\nбланка от менеджера;
:Заполнение и передача обратно менджеру;

|Экономист отдела банка по работе \nсо счетами клиентов|
:Проверка средств на счете;
if (Средства на счете доступны?) then (да)
    :Печать “Сальдо счета позволяет”;
    :Бронирование средств ;
    :Передача бланка и контракта в\nотдел международных расчетов;
else (нет)
    :Информирование менеджера о недостатке средств;
    stop;
endif

|Сотрудник отдела международных расчетов|
:Получение бланка и контракта;
:Проверка правильности заполнения;
if (Бланк заполнен верно?) then (да)
    :Передача бланка\nв отдел корреспондентских отношений;
else (нет)
    :Передача обратно менеджеру\nфирмы для исправления;
    stop;
endif

|Позиционер отдела \n корреспондентских отношений|
:Бронирование средств ;
:Получение бланка\nс кодом корреспондента\nи датой валютирования;

|Сотрудник отдела международных расчетов|
:Получение бланка заявления на международный перевод от позиционера;
:Оформление заявления на перевод \nв формате телекса или СВИФТ МТ100\nи мемориального ордера с проводками;
:Передача оформленных документов\nи контракта начальнику отдела\nмеждународных расчетов;

|Начальник отдела международных расчетов|
:Подпись документов;
:Возврат оформленных документов обратно\nсотруднику отдела международных расчетов;

|Сотрудник отдела международных расчетов|
:Получение оформленных документов;
fork
  :Передача МТ100 в формате телекса или СВИФТ в отдел телекса или СВИФТ;
  fork
  |Отдел телекса|
  :Отправка заявлений на перевод (МТ100)\nкорреспонденту Банка;
  fork again
  |Отдел СВИФТ|
  :Отправка заявлений на перевод (МТ100)\nкорреспонденту Банка;
  end fork
fork again
  |Сотрудник отдела международных расчетов|
  :Передача мемориального ордера\nв бухгалтерию;

|Бухгалтерия|
:Bухгалтер получает мемориальный ордер \nи заносит его в операционный день банка;

end fork
stop
@enduml
